(define path (string-append (get-environment-variable "HOME") "/picture-language/sicp/"))

(load-file (string-append path "abstract-data.scm"))
(load-file (string-append path "segments.scm"))
(load-file (string-append path "painter.scm"))
(load-file (string-append path "frame.scm"))
(load-file (string-append path "demo.scm"))
(load-file (string-append path "fractal.scm"))
(if (= 3 (gtk-major-version))(load-file (string-append path "roger.scm")))
(load-file (string-append path "segments-fish.scm"))
